config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :admins
  resources 'contacts', only: [:new, :create]
  resources :sessions,              only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

  root 'site_pages#home'

  get '/about', to: 'site_pages#about'

  get '/blog', to: 'site_pages#blog'

  get '/contact', to: 'contacts#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  before_save :create_remember_token

  has_many :posts

  has_secure_password

  validates :username,  presence: true, length: { minimum: 5 }

  validates :password, length: { minimum: 6 }, :on => :create, allow_blank: true
  validates :password_confirmation, presence: true, :on => :create

  # Returns the hash digest of the given string.
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def Admin.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private

  def create_remember_token
    self.remember_token = Admin.new_token
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :content, presence: true
  validates :author, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :comments
  attribute :phone
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        subject: 'ESABOL Contact',
        to: 'esabolhealthyliving@gmail.com',
        from: %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :admin
  has_many :comments

  validates :author, presence: true
  validates :content, presence: true
  validates :title, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  private

  def admin_params
    params.require(:admin).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.friendly.find(params[:post_id])

    if @post.comments.create(comment_params)
      redirect_to @post,
                  notice: 'Comment was successfully created.'
    else
      redirect_to @post,
                  alert: 'Error creating comment, ' + @post.errors
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.friendly.find(params[:post_id])

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
      render :new
    else
      flash.now[:alert] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,         only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user,      except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to blog_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content, :author)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by(username: params[:session][:username])
    if admin && admin.authenticate(params[:session][:password])
      login admin
      redirect_to root_path,
                  notice: 'You are now logged in!'
    else
      flash.now.alert = 'Invalid login credentials. Contact Site Admin if you forgot your credentials.'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_path,
                notice: 'You have been logged out successfully!'
  end
end

app/controllers/site_pages_controller.rb
class SitePagesController < ApplicationController
  def home
  end

  def about
  end

  def blog
    @post = Post.friendly.last
    unless @post
      redirect_to root_path,
                  notice: 'Sorry, there is currently no blog post. Contact us if you have something to post.'
    end
  end

  def contact
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title of a page
  def full_title(page_title)
    base_title = 'ESABOL'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def friendly_date(d)
    d.strftime("%B %e, %Y")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(admin)
    cookies[:remember_token] = admin.remember_token
    self.current_user = admin
  end

  def current_user=(admin)
    @current_user = admin
  end

  def current_user
    @current_user ||= Admin.find_by_remember_token(cookies[:remember_token])
  end

  def logged_in?
    !self.current_user.nil?
  end

  def logged_in_user
    if !logged_in?
      redirect_to login_path,
                  alert: 'Sorry, you need to be logged in to access that page.'
    end
  end

  def logout
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/site_pages_helper.rb
module SitePagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.author %> said:</p>

<blockquote class="comment">
  <%= raw comment.content %>
</blockquote>

<% if logged_in? %>
    <%= link_to 'Remove comment', [comment.post, comment],
            method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
      <div>
        <a href="#" data-dismiss="alert">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<% provide(:row_info, 'Contact Us') %>

<div class="container">
  <h2>Contact</h2>
  <div class="row" id="contact">
    <%= render 'shared/flash_msg' %>
    <div class="col-sm-8">
      <p>
        We'd love to hear from you. Fill the form below to make a booking or ask questions.
        Your details will be kept private.
      </p>
      <div class="jumbotron" id="form_container">
        <%= simple_form_for @contact do |f| %>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, required: true, class: 'form-control', placeholder: 'First and last name please' %>
                  <%= f.label :phone %>
                  <%= f.phone_field :phone, class: 'form-control', placeholder: 'What is your phone number?' %>
                  <%= f.label :email %>
                  <%= f.email_field :email, required: true, class: 'form-control', placeholder: 'What is your email address?' %>
                  <div class= "hidden">
                    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <label for="comments">Comment/Questions:</label>
                <%= f.text_area :comments, required: true, class: 'form-control', placeholder: 'Write your message here!' %>
              </div>
            </div>
            <%= f.submit 'Submit', class: 'btn btn-primary pull-right' %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="jumbotron" id="contact-details">
        <h4><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Company Addresses</h4>
        <address>
          <strong>ESABOL Juice and Smoothie Bar</strong><br>
          Dwarf Shop 3<br>
          FUTA Community Shopping Plaza<br>
          Oba-Nla Campus, FUTA<br>
          Akure, Nigeria.
        </address>
        <address>
          <strong>ESABOL Juice and Smoothie Bar</strong><br>
          FUTA Sports Complex<br>
          Behind Hilltop Auditorium<br>
          Oba-Nla Campus, FUTA<br>
          Akure, Nigeria.
        </address>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_carousel.html.erb
<div class="row">
  <div id="pictures" class="col-sm-12 owl-carousel owl-theme">
    <div class="item" id="slide-1"><%= image_tag 'fullimage8.jpg', alt: 'ESABOL' %></div>
    <div class="item" id="slide-2"><%= image_tag 'fullimage1.jpg', alt: 'FRUITY' %></div>
    <div class="item" id="slide-3"><%= image_tag 'fullimage2.jpg', alt: 'FRUITY' %></div>
    <div class="item" id="slide-4"><%= image_tag 'fullimage3.jpg', alt: 'FRUITY' %></div>
    <div class="item" id="slide-5"><%= image_tag 'fullimage4.jpg', alt: 'FRUITY' %></div>
    <div class="item" id="slide-6"><%= image_tag 'fullimage5.jpg', alt: 'FRUITY' %></div>
    <div class="item" id="slide-8"><%= image_tag 'fullimage7.jpg', alt: 'FRUITY' %></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer container-fluid">
  <div class="container">
    <div id="footer-row-1" data-role="footer" class="row">
      <div class="col-sm-4">
        <h4>Contact us</h4>
        <div id="wrapper">
          <section id="primary">
            <p>If you have an offer, or you need further information, do not hesitate to contact us!</p>
            <p>Please only use phone contact for urgent inquiries.</p>
          </section>
          <section id="secondary">
            <ul class=contact-info>
              <li class="phone"><a id="first-phone" href="tel:08033500516">08033500516;</a> <a id="second-phone" href="tel:08058203168">08058203168</a></li>
              <li class="mail"><a href="mailto:info@esabolhealthyliving.com">info@esabolhealthyliving.com</a></li>
            </ul>
          </section>
        </div>
      </div>
      <div class="col-sm-4">
        <h4>Visit us:</h4>
        <address>
          <strong>ESABOL Juice and Smoothie Bar</strong><br>
          FUTA Sports Complex<br>
          Behind Hilltop Auditorium<br>
          Oba-Nla Campus, FUTA<br>
          Akure, Nigeria.
        </address>
      </div>
      <div class="col-sm-4">
        <h4>Quick Links</h4>
        <% @post = Post.last %>
        <ul style="list-style: none; padding-left: 7px;">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path %></li>
          <% if @post %>
            <li><%= link_to @post.title, @post %></li>
          <% end %>
          <% unless logged_in? %>
            <%= link_to 'Admin Login', login_path %>
          <% end %>
        </ul>
      </div>
    </div>
    <br>
    <div id="footer-row-2" class="row">
      <%= link_to (image_tag 'esabol_logo.png', alt: 'ESABOL', class: 'logo'), root_path %><br>
      &copy 2016. All rights reserved.
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header id="navbar" class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <%= link_to (image_tag 'esabol_logo.png', alt: 'ESABOL', class: 'logo'), root_path %>
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <nav class="collapse navbar-collapse" id="navbar-collapse">
        <% @post = Post.last %>
        <ul id="nav-links" class="nav navbar-nav navbar-right">
          <li><%= nav_link_to 'home', root_path %></li>
          <li><%= nav_link_to 'about', about_path %></li>
          <li><%= nav_link_to 'contact', contact_path %></li>
          <li><%= nav_link_to 'blog', blog_path, class: 'stud' %></li>
          <% if logged_in? %>
              <li id="fat-menu" class="pull-right dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-user"></i> Admin <b class="caret"></b>
                </a>
                <ul id="dropdown" class="dropdown-menu">
                  <li><%= link_to 'Add a Post', new_post_path %></li>
                  <li id="divider" class="divider"></li>
                  <li>
                    <%= link_to 'Log out', logout_path, method: 'delete' %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li class="pull-right" style="color: #fff;"><%= link_to content_tag(:span, '', class: 'fa fa-user login-image'), login_path %></li>
          <% end %>
        </ul>
      </nav><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</header>

app/views/layouts/_row_one.html.erb
<div id="row-1" class="row text-center">
  <%= image_tag 'favicon.png', class: 'inline inline-image' %>
  <div class="inline">
    <h3>Visit Our Juice Bar</h3>
    <h4>in Akure, Nigeria</h4>
  </div>
   <%= image_tag 'favicon.png', class: 'inline inline-image' %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic' rel='stylesheet' type='text/css'>
      <%= favicon_link_tag 'favicon.png' %>
      <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
    </head>
    <body>
        <div id="content">
          <%= render 'layouts/header' %>
          <%= render 'shared/flash_msg' %>
          <%= yield %>
          <%= render 'layouts/footer' %>
        </div>
    </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this message from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.text_field :title, class:'form-control', placeholder:'Post title', required: true %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.text_field :author, class:'form-control', placeholder:'Author', required: true %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.cktext_area :content, :ckeditor => {:language => 'en'}, required: true %>
    </div>
    <div class="actions">
      <%= f.submit class:'btn btn-primary' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="container">
  <h2 class="text-center blog-page-title"><%= image_tag 'blog_logo.png', alt: 'ESABOL', class: 'blog_logo' %></h2>
  <div class="row">
    <div id="post" class="col-sm-9">
      <div id="show-post">
        <h3 class="blog-title">
          <%= @post.title %>
          <small><p>by <%= @post.author %><br>
            <em><%= friendly_date @post.created_at %></em></p></small>
        </h3>
        <em>
          <p>
            <a href="#comments-start"><i class="fa fa-comment-o"></i><%= @post.comments.count %></a>
            <span class="pull-right">
                Last updated <%= time_ago_in_words @post.updated_at %> ago
              <% if logged_in? %>
                    <%= link_to content_tag(:span, '', class: 'fa fa-trash-o') , @post,
                                method: :delete, data: { confirm: 'Are you sure?'} %>
                  <%= link_to content_tag(:span, '', class: 'fa fa-edit') , edit_post_path(@post) %>
                <% end %>
            </span>
          </p>
        </em>
        <hr>
        <div class="post-content"><%= raw @post.content %></div>
        <br id="comments-start">

        <h3>Comments</h3>

        <%= render @post.comments %>

        <%= form_for [@post, @post.comments.build] do |f| %>
            <div class='form-group'>
              <%= f.text_field :author, class: 'form-control', placeholder:'Your name', required:'required' %>
            </div>
            <div class='form-group'>
              <%= f.cktext_area :content, :ckeditor => {language: 'en', toolbar: 'comment'}, required: true, class: 'form-control', placeholder:'Your comments/questions' %>
            </div>
            <div class='actions'>
              <%= f.submit class:'btn btn-primary' %>
            </div>
        <% end %>
      </div>
    </div>
    <div id="sidebar" class="col-sm-3">
      <p class="text-justify">
        Get the latest on health benefits of foods, fruits and fruit juices.
        <% link_to 'Contact us', new_contact_path %> Please contact us if you have any information to add.
        The information will be credited to you.
      </p>
      <h2>Recent Posts</h2>
      <ul>
        <% posts = Post.all.order('created_at DESC') %>
        <% posts.each do |post| %>
            <li><%= link_to post.title, post %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "#{@post.title}") %>

<div id="edit-post" class="container">
  <h2>Edit post</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @post %> |
</div>

app/views/posts/new.html.erb
<% provide(:title, 'Posts') %>

<div id="new-post" class="container">
  <h2>New Post</h2>

  <%= render 'form' %>

  <%= link_to 'Back', blog_path %>
</div>

app/views/posts/show.html.erb
<% provide(:title, "#{@post.title}") %>
<% provide(:row_info, 'View Our Blog') %>

<div class="container">
  <h2 class="text-center blog-page-title">EHLS Blog</h2>
  <div class="row">
    <div id="post" class="col-sm-9">
      <div id="show-post">
        <h3 class="blog-title">
          <%= @post.title %>
          <small><p>by <%= @post.author %><br>
            <em><%= friendly_date @post.created_at %></em></p></small>
        </h3>
        <em>
          <p>
            <a href="#comments-start"><i class="fa fa-comment-o"></i><%= @post.comments.count %></a>
            <span class="pull-right">
                Last updated <%= time_ago_in_words @post.updated_at %> ago
                <% if logged_in? %>
                    <%= link_to content_tag(:span, '', class: 'fa fa-trash-o') , @post,
                                                         method: :delete, data: { confirm: 'Are you sure?'} %>
                      <%= link_to content_tag(:span, '', class: 'fa fa-edit') , edit_post_path %>
                <% end %>
            </span>
          </p>
        </em>
        <hr>
        <div class="text-justify post-content"><%= raw @post.content %></div>
        <br id="comments-start">

        <h3>Comments</h3>

        <%= render @post.comments %>

        <%= form_for [@post, @post.comments.build] do |f| %>
            <div class='form-group'>
              <%= f.label :author %><br>
              <%= f.text_field :author, class: 'form-control', placeholder:'Your name', required:'required' %>
            </div>
            <div class='form-group'>
              <%= f.label :content %><br>
              <%= f.cktext_area :content, :ckeditor => {language: 'en', toolbar: 'comment'}, required: true, class: 'form-control', placeholder:'Your comments/questions' %>
            </div>
            <div class='actions'>
              <%= f.submit class:'btn btn-primary' %>
            </div>
        <% end %>
      </div>
    </div>
    <div id="sidebar" class="col-sm-3">
      <p class="text-justify">
        Get the latest on health benefits of foods, fruits and fruit juices.
        <% link_to 'Contact us', new_contact_path %> if you have any information to add. The information will be credited to you.
      </p>
      <h2>Recent Posts</h2>
      <ul>
        <% posts = Post.all.order('created_at DESC') %>
        <% posts.each do |post| %>
            <li><%= link_to post.title, post %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flash_msg.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

app/views/site_pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:row_info, 'About Us') %>

<div class="container-fluid">
  <div class="row">
    <h2 class="text-center">About ESABOL Healthy Living Services</h2>
    <div class="col-sm-3">
      <blockquote>
        <p class="text-justify quotes">Beloved, I wish above all things that thou mayest prosper and be in health,
          even as thy soul prospereth.</p>
        <footer class="text-right">
          God<br>
          <cite title="Source Title">3 John 1:2</cite>
        </footer>
      </blockquote>
      <hr>
      <blockquote>
        <p class="text-justify quotes">Health is the greatest form of wealth, and right feeding is one the greatest factors of health.
          As the common going says, "you are what you eat, and drink".</p>
        <div class="text-right">
          <%= image_tag 'profesan.jpg', alt: 'Prof. EA Aderinola', id: 'profesan', class: "img img-thumbnail img-circle" %>
        </div>
        <footer class="text-right">
          Professor Esan A. Aderinola<br>
          <cite title="Source Title">Founder/CEO</cite>
        </footer>
      </blockquote>
    </div>
    <div class="col-sm-6">
      <h3>How EHLS Started</h3>
      <p id="about" class="text-justify">
        There were just a few juicers. Various home-made juices would be enjoyed by many people, even without knowledge of the Health
        benefits. Along the line, research was made into the health benefits of some of these fruit juices, which you can find on
        our <%= link_to 'blog', blog_path %>.
      </p>
      <p class="text-justify">
        Thus, ESABOL Healthy Living Services was founded in 2009 by Professor Esan A. Aderinola, to the Glory of God, and for the benefit
        of mankind. Since then, ESABOL has grown from a family business into a large business, providing healthy living services, selling
        fresh fruit juices, and servicing events within and outside the home state - Ondo State, Nigeria.
      </p>

      <h3>What we do at EHLS</h3>
      <p class="text-justify">
        We provide fresh fruit juices, including Carrot, Cucumber, Watermelon, Orange, Shaddock, Grape, Pineapple and
        Cabbage juices; Smoothies and Fruit Salad.
        <bold>Our Products are 100% natural (no preservatives), undiluted and without sweeteners.</bold>
      </p>
      <p class="text-justify">
        We can also produce and serve on the spot at your parties and ceremonies. On your call, we can also deliver our products at your
        door step or offices. They are not only therapeutic, they are rejuvenating and reinvigorating. Remember:
        <p class="text-center"><em>"You are what you eat and drink"</em></p>
      </p>
      <br>
      <%= image_tag 'about-page-picture-1.jpg', class: "img img-responsive img-rounded img-thumbnail about-image" %>
      <p class="text-center"><em>ESABOL orange juice, watermelon juice, carrot juice and fruit salad.</em></p>
      <br>
      <p class="text-justify">
        EHLS is not primarily a profit-making organization. We exist because we have a passion to see you healthy. Knowing that food is the
        primary determinant of health, our goal is to provide what you need to stay healthy - food, drink, counseling, health talks, <em>etc.</em>.
      </p>
      <p class="text-justify">
        We're not very far from you. Visit us today, and your health can only get better!
      </p>
    </div>
    <div class="col-sm-3 text-center">
      <div id="sidebar-slides" class="owl-carousel">
        <div class="item"><%= image_tag 'slide-1.jpg', class: "lazyOwl" %></div>
        <div class="item"><%= image_tag 'slide-2.jpg', class: "lazyOwl" %></div>
      </div>
    </div>
  </div>
</div>

app/views/site_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<% provide(:row_info, 'View Our Blog') %>

<%= render @post %>